name: "ESP32 PhotoFrame Server"
version: "v1.4.8"
slug: "esp32-photoframe-server"
description: "Image server for ESP32 PhotoFrame"
url: "https://github.com/aitjcize/esp32-photoframe-server"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
ports:
  9607/tcp: 9607
ingress: true
ingress_port: 9607
panel_icon: mdi:image-frame
panel_title: ESP32 PhotoFrame Server
webui: http://[HOST]:[PORT:9607]
map:
  - config:rw
options: {}
schema: {}
environment:
  DB_PATH: /data/photoframe.db
  DATA_DIR: /data
